package com.github.feiyongjing.service.EnglishWordsFactoryImpl;

import com.github.feiyongjing.service.factory.EnglishWordsFactory;

import java.util.HashMap;
import java.util.LinkedHashMap;

public class ComputerWords implements EnglishWordsFactory {
    @Override
    public HashMap<String, String> getEnglishWords() {
        LinkedHashMap<String, String> questionsAndAnswers = new LinkedHashMap<>();
//        HashMap<String, String> questionsAndAnswers = new HashMap<>();
        questionsAndAnswers.put("存在；出现；活着", "exists");
        questionsAndAnswers.put("期满；终止；死亡；呼气", "expire");
        questionsAndAnswers.put("存留，坚持；持续，固执", "persist");
        questionsAndAnswers.put("正则", "pattern");
        questionsAndAnswers.put("倾倒；丢下", "dump");
        questionsAndAnswers.put("随机的；任意的；胡乱的", "random");
        questionsAndAnswers.put("范围", "range");
        questionsAndAnswers.put("增量", "increment");
        questionsAndAnswers.put("减量", "decrement");
        questionsAndAnswers.put("弹出", "pop");
        questionsAndAnswers.put("在···之后", "after");
        questionsAndAnswers.put("中心", "pivot");
        questionsAndAnswers.put("在···之前", "before");
        questionsAndAnswers.put("源；源头", "source");
        questionsAndAnswers.put("目的地；终点", "destination");
        questionsAndAnswers.put("推动；增加", "push");
        questionsAndAnswers.put("修剪；切除", "trim");
        questionsAndAnswers.put("成员；会员", "member");
        questionsAndAnswers.put("卡片；纸牌；明信片", "card");
        questionsAndAnswers.put("差异", "diff");
        questionsAndAnswers.put("存储", "store");
        questionsAndAnswers.put("埋葬", "inter");
        questionsAndAnswers.put("联合", "union");
        questionsAndAnswers.put("独特的，稀罕的；唯一的，独一无二的", "unique");
        questionsAndAnswers.put("下降；终止", "drop");
        questionsAndAnswers.put("使用，运用", "use");
        questionsAndAnswers.put("版本", "version");
        questionsAndAnswers.put("评论；摘要；附注", "remarks");
        questionsAndAnswers.put("默认", "default");
        questionsAndAnswers.put("主要的；初级的；基本的", "primary");
        questionsAndAnswers.put("改变，更改", "alter");
        questionsAndAnswers.put("分数", "score");
        questionsAndAnswers.put("和……在一起", "with");
        questionsAndAnswers.put("排；等级；军衔；队列", "rank");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
        //        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");
//        questionsAndAnswers.put("", "");

        return questionsAndAnswers;
    }
}
